# Generated by Django 5.0.1 on 2024-01-09 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('927392f1-cbed-47d7-a760-95f269dca57c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('927392f1-cbed-47d7-a760-95f269dca57c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel_booking',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('927392f1-cbed-47d7-a760-95f269dca57c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel_images',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.hotel'),
        ),
        migrations.AlterField(
            model_name='hotel_images',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('927392f1-cbed-47d7-a760-95f269dca57c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
