# Generated by Django 5.0.1 on 2024-01-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_amenities_uid_alter_hotel_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='end_at',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='start_at',
            new_name='start_date',
        ),
    ]
